### ISSUE TITLE
shouldn't z_loc  point to $_Z_DATA, ?

### ISSUE THREAD

**Issue by westofer** [ask1234560/ranger-zjumper#2]
if a I sets up custom `.z` location with $_Z_DATA, 
I get the following error `Errno 2 no such file or directory /home/username/.z`
here is the code 
https://github.com/ask1234560/ranger-zjumper/blob/c209343386a979671e06d2281bb34be84ce137f7/zjumper_ranger.py#L13-L15

**Comment by westofer** [comment]
this fixed it for me

https://github.com/westofer/ranger-zjumper/blob/6274765eae6ba681db65fabc796781a6f0ba1751/zjumper_ranger.py#L13-L15

```diff
-           z_loc = getenv("HOME")+"/.z" 
+         z_loc = getenv("_Z_DATA") or getenv("HOME")+"/.z"
```

**Comment by ananthu-sk** [comment]
Thanks for fixing
