### ISSUE TITLE
Rename zjumper_ranger.py to __init__.py to simplify installation

### ISSUE THREAD

**Issue by Anomalocaridid** [ask1234560/ranger-zjumper#4]
Ranger added the ability to load plugins from a directory inside the plugins folder. However, this requires that the entry file is named \_\_init__.py. This would allow users to install the ranger-zjumper plugin by simply cloning its git repository into the plugins folder as well as eliminating the need to copy the file into the plugins folder every time the plugin gets updated.

**Comment by ananthu-sk** [comment]
Thank you for raising the issue. I have renamed the file.

**Comment by Anomalocaridid** [comment]
Thank you!
