### ISSUE TITLE
Does it still work with zsh-z?

### ISSUE THREAD

**Issue by andreatitolo** [ask1234560/ranger-zjumper#5]
Hi! Is the v2 of this plugin still compatible with [zsh-z](https://github.com/agkozak/zsh-z)? 
Just asking since the readme doesn't mention it anymore and the code only reference bash. If I want to use with zsh-z should I install a previous version?

Thank you! :)

**Comment by ananthu-sk** [comment]
Hi, the v2 branch currently only supports [z](https://github.com/rupa/z). You can use the master branch which still supports the [zsh-z](https://github.com/agkozak/zsh-z).

**Comment by andreatitolo** [comment]
Just tried and works like a charm, thank you for your quick answer! :)
